postgres:
  url-postfix: postgresql://localhost:5432/postgres
  username: postgres
  password: postgres

spring:
  r2dbc:
    url: r2dbc:${postgres.url-postfix}
    username: ${postgres.username}
    password: ${postgres.password}
    pool:
      enabled: true
      initial-size: 10
      max-size: 30
      max-idle-time: 1m
  flyway:
    url: jdbc:${postgres.url-postfix}
    user: ${postgres.username}
    password: ${postgres.password}
    baseline-on-migrate: true
    baseline-version: 0
    # TODO: disable for production - just for POC versions!
    clean-on-validation-error: true
