# User properties ==================
application:
  namespace:
    default: default
  storage:
    enabled: false
    database:
      url: postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
  loader:
    type: directory
    enabled: true
    force-update: false
    location: /data


# Internal properties ==================
spring:
  r2dbc:
    url: r2dbc:${application.storage.database.url}
    username: ${application.storage.database.username}
    password: ${application.storage.database.password}
    pool:
      enabled: true
      initial-size: 10
      max-size: 30
      max-idle-time: 1m
  flyway:
    url: jdbc:${application.storage.database.url}
    user: ${application.storage.database.username}
    password: ${application.storage.database.password}
    baseline-on-migrate: true
    baseline-version: 0
    # TODO: disable for production - just for POC versions!
    clean-on-validation-error: false
