CREATE TABLE NAMESPACES
(
    NAME   VARCHAR(100) PRIMARY KEY,
    STATUS VARCHAR(40) NOT NULL
);

CREATE TABLE VERSIONS
(
    ID        VARCHAR(100) PRIMARY KEY,
    NAMESPACE VARCHAR(100) NOT NULL,
    VERSION   VARCHAR(100) NOT NULL
);